[package]
name = "divoom-ditoo-pro-controller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["text", "all-image-formats", "video"]
text = ["dep:fontdue", "dep:fontconfig", "dep:bdf-parser"]
all-image-formats = ["image/default"]
video = ["dep:libmpv2-sys"]

[dependencies]
clap = { version = "4.5.30", features = ["derive"] }
tokio = { version = "1.43.0", features = ["rt-multi-thread", "macros", "io-util", "sync", "time", "signal"] }
env_logger = "0.11.6"
log = "0.4.26"
hex = "0.4.3"
image = { version = "0.25.5", default-features = false, features = ["gif", "png", "jpeg", "bmp", "webp"] }
byteorder = "1.5.0"
bitstream-io = "2.6.0"
chrono = "0.4.40"
indexmap = "2.7.1"
fontdue = { version = "0.9.3", optional = true }
fontconfig = { version = "0.10.0", optional = true }
csscolorparser = "0.8.2"
bdf-parser = { version = "0.1.0", optional = true }
libmpv2-sys = { version = "4", optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
futures = "0.3.31"
bluer = { version = "0.17.4", features = ["rfcomm", "bluetoothd"] }
uuid = "1.20.0"

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6"
objc2-foundation = "0.3"
objc2-io-bluetooth = "0.3"

[dev-dependencies]
spectral = "0.6.0"

[lints.clippy]
panic = "warn"
expect_used = "warn"
unwrap_used = "warn"
